[templates]
foot.template = "foot.ini"
foot.target = "~/.config/foot/colors.ini"
foot.pywal = true

zathura.template = "zathurarc"
zathura.target = "~/.config/zathura/zathurarc"
zathura.pywal = true

fuzzel.template = "fuzzel.ini"
fuzzel.target = "~/.config/fuzzel/colors.ini"
fuzzel.pywal = true

qutebrowser.template = "qutebrowser.py"
qutebrowser.target = "~/.config/qutebrowser/colors.py"
qutebrowser.pywal = true

btop.template = "btop.theme"
btop.target = "~/.config/btop/themes/wallust.theme"
btop.pywal = true

tmux.template = "tmux.conf"
tmux.target = "~/.config/wallust/tmux-colors.conf"
tmux.pywal = true
